# makefile.

# In software development, Make is a build automation tool that automatically 
# builds executable programs and libraries from source code by reading files 
# called Makefiles which specify how to derive the target program.




# To use a makefile you must provide two pieces of information
#   1) Dependency information between resource files.
#   2) Compiler commands

# comment
# multi-line comments:
# 1) 

ifeq(1,2)



endif


output: main